# Generated by Django 4.2.7 on 2023-12-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_auction_listings_image_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listings",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
