# Generated by Django 4.2.7 on 2023-12-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_auction_listings_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listings",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
