# Generated by Django 4.2.7 on 2023-12-04 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_remove_auction_listings_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listings",
            name="user_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
