# Generated by Django 4.2.7 on 2023-12-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_watchlist_remove_auction_listings_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="auction_listing_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="bids",
            name="user_id",
            field=models.BigIntegerField(),
        ),
    ]
