# Generated by Django 4.2.7 on 2023-12-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_alter_bids_auction_listing_id_alter_bids_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="auction_listing_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="comments",
            name="user_id",
            field=models.BigIntegerField(),
        ),
    ]
