# Generated by Django 4.2.7 on 2023-12-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_userfollowinguser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollowinguser",
            name="follower_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="userfollowinguser",
            name="following_id",
            field=models.IntegerField(),
        ),
    ]
